### ISSUE TITLE
Parse based on tzfile

### ISSUE THREAD

**Issue by breezewish** [chronotope/chrono-tz#25] opened 2018-09-04 03:21 UTC
IANA databases are provided in two formats, human readable format and machine readable binary format (tzfile). Currently chrono-tz parse time zone from a human readable format. It would be better to parse from a tzfile, so that time zone info can be also loaded from a local tzfile like `/etc/localtime`.

**Comment by pitdicker** [comment] 2024-04-05 13:54
In general I don't think 'it would be better to parse from a tzfile'. The text files provide more information and are a closer match to the rule as they are specified in human terms. At the end the result should be the same of course.

For loading a TZif file at runtime I'd like to close this as a duplicate of #73 (although this issue is older).

**Closed by pitdicker** 2024-04-05 13:54 UTC
